[package]
name = "parser"
version = "0.1.0"
edition = "2021"

[profile.perf]
inherits = "release"
debug = true

[dependencies]
camino = "1.1.1"
anyhow = "1.0.89"
lsp-server = "0.7.7"
lsp-types = "0.97.0"
ropey = "1.6.1"
serde = "1.0.210"
serde_json = "1.0.128"
url = "2.5.2"
